### ISSUE TITLE
MongoDB 인스턴스 띄우기

### ISSUE THREAD

**Issue by henry-hs-choi** [backs-up/nonamemo#2]
Atlas에 MongoDB 인스턴스 띄워서 문서로 공유하기

**Comment by superjisonic** [comment]
(진행상황)
- 열심히 몽고디비 공부함
- 직접 몽고디비 인스턴스 만듦 (mongodb+srv://nona_user:<password>@nonaapp.idree.mongodb.net/<dbname>?retryWrites=true&w=majority)
- mongoTemplate 사용하여 service, controller 까지 코딩

**Comment by superjisonic** [comment]
몽고디비를 연결했습니다....!
음,, 제가 혼자 공부하느라 제 Atlas의 계정을 새로 만들어서 연결해버렸어요,,

[과정]
**1. Atlas 에 계정 생성 후 DB cluster 및 인스턴스 생성**

참고 - (https://medium.com/@mnnk202/spring-boot-and-mongodb-atlas-a2df466e8949)

> 1-1. user계정과 pwd, dbname까지 세팅하면 url이 자동으로 생성됨

**2. Data Insert (그냥 수기로 insert함)**

`
{"_id":
    {"$oid":"5f86e8c539d341342ef03966"}
    ,"userId":"supersonic"
    ,"url":"https://www.google.com/search?q=github+profile&rlz=1C5CHFA_enKR732KR732&oq=github+profi&aqs=chrome.0.0j69i57j0l3j69i60l3.19577j1j1&sourceid=chrome&ie=UTF-8"
    ,"content":"오늘은 너무나도 피곤한 날이지만 노나메모 앱 개발을 해봅니당. 본가가서 초코 뱃살 만지작하고 싶다."
    ,"likedUsers":["admin","user","sonic",""]
    ,"createdAt":{"$date":{"$numberLong":"1602633600000"}}}
`

**3. 위의 url을 application.properties에 붙여넣음**

`
spring.data.mongodb.uri=mongodb+srv://nona_user:nonanona123@nonaapp.idree.mongodb.net/nonadb?retryWrites=true&w=majority
spring.data.mongodb.database=nonadb
`

**4. Service에서 MongoTemplate 세팅**

`
@Autowired
    public void setMongoTemplate(MongoTemplate mongoTemplate){
        this.mongoTemplate = mongoTemplate;
    }
`

**5. MongoTemplate 메소드 사용하여 data fetch**

`
public List<Memo> selectMemoData(){
        List<Memo> memoList = mongoTemplate.findAll(Memo.class);
        return memoList;
    }
`

**6. controller 작성**

 - 화면은 따로 만들지 않았으므로, 여기서 System.out.println()으로 콘솔에 찍어보세요...
 > - 저는 Memo.java에서 toString 오버라이딩 해주고 controller에서 memo.toString()했습니다.

**7.  http://localhost:8080/all** 

 - 콘솔에 잘 찍혀 나옵니다.
![image](https://user-images.githubusercontent.com/24906021/96110133-6b60bb80-0f1a-11eb-9241-ddce483d65f6.png)
